[colors.primary]
background = "0x22272e"
foreground = "0xadbac7"

[colors.cursor]
cursor = "0xadbac7"
text = "0x22272e"

[colors.normal]
black = "0x545d68"
red = "0xf47067"
green = "0x57ab5a"
yellow = "0xc69026"
blue = "0x539bf5"
magenta = "0xb083f0"
cyan = "0x39c5cf"
white = "0x909dab"

[colors.bright]
black = "0x636e7b"
red = "0xff938a"
green = "0x6bc46d"
yellow = "0xdaaa3f"
blue = "0x6cb6ff"
magenta = "0xdcbdfb"
cyan = "0x56d4dd"
white = "0xcdd9e5"

[font]
size = 10.5

[font.normal]
family = "Noto Sans Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[scrolling]
history = 0

[window]
decorations = "none"

[shell]
program = "/usr/bin/tmux" 
args = ["new-session"]
